// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/image.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImagesRequest) Reset() {
	*x = GetImagesRequest{}
	mi := &file_proto_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesRequest) ProtoMessage() {}

func (x *GetImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesRequest.ProtoReflect.Descriptor instead.
func (*GetImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{0}
}

func (x *GetImagesRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type GetImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags      []string               `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Containers    int64                  `protobuf:"varint,5,opt,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_proto_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{1}
}

func (x *GetImageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetImageResponse) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *GetImageResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *GetImageResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetImageResponse) GetContainers() int64 {
	if x != nil {
		return x.Containers
	}
	return 0
}

type GetImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*GetImageResponse    `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImagesResponse) Reset() {
	*x = GetImagesResponse{}
	mi := &file_proto_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesResponse) ProtoMessage() {}

func (x *GetImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesResponse.ProtoReflect.Descriptor instead.
func (*GetImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{2}
}

func (x *GetImagesResponse) GetImages() []*GetImageResponse {
	if x != nil {
		return x.Images
	}
	return nil
}

type GetImageDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageDetailsRequest) Reset() {
	*x = GetImageDetailsRequest{}
	mi := &file_proto_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageDetailsRequest) ProtoMessage() {}

func (x *GetImageDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetImageDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{3}
}

func (x *GetImageDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetImageDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags      []string               `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	Created       string                 `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageDetailsResponse) Reset() {
	*x = GetImageDetailsResponse{}
	mi := &file_proto_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageDetailsResponse) ProtoMessage() {}

func (x *GetImageDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetImageDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{4}
}

func (x *GetImageDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetImageDetailsResponse) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *GetImageDetailsResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *GetImageDetailsResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetImageDetailsResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GetImageDetailsResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetImageDetailsResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RemoveImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	PruneChildren bool                   `protobuf:"varint,3,opt,name=prune_children,json=pruneChildren,proto3" json:"prune_children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_proto_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveImageRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RemoveImageRequest) GetPruneChildren() bool {
	if x != nil {
		return x.PruneChildren
	}
	return false
}

type RemoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RemoveImageResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_proto_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveImageResponse) GetResults() []*RemoveImageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RemoveImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       string                 `protobuf:"bytes,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Untagged      string                 `protobuf:"bytes,2,opt,name=untagged,proto3" json:"untagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResult) Reset() {
	*x = RemoveImageResult{}
	mi := &file_proto_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResult) ProtoMessage() {}

func (x *RemoveImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResult.ProtoReflect.Descriptor instead.
func (*RemoveImageResult) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveImageResult) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

func (x *RemoveImageResult) GetUntagged() string {
	if x != nil {
		return x.Untagged
	}
	return ""
}

type PullImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	RegistryAuth  string                 `protobuf:"bytes,2,opt,name=registry_auth,json=registryAuth,proto3" json:"registry_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageRequest) Reset() {
	*x = PullImageRequest{}
	mi := &file_proto_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageRequest) ProtoMessage() {}

func (x *PullImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageRequest.ProtoReflect.Descriptor instead.
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{8}
}

func (x *PullImageRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PullImageRequest) GetRegistryAuth() string {
	if x != nil {
		return x.RegistryAuth
	}
	return ""
}

type PullImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageResponse) Reset() {
	*x = PullImageResponse{}
	mi := &file_proto_image_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageResponse) ProtoMessage() {}

func (x *PullImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageResponse.ProtoReflect.Descriptor instead.
func (*PullImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{9}
}

func (x *PullImageResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type BuildImageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BuildContext      []byte                 `protobuf:"bytes,1,opt,name=build_context,json=buildContext,proto3" json:"build_context,omitempty"`
	Dockerfile        string                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	DockerfileContent string                 `protobuf:"bytes,3,opt,name=dockerfile_content,json=dockerfileContent,proto3" json:"dockerfile_content,omitempty"`
	Tags              []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	NoCache           bool                   `protobuf:"varint,5,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	BuildArgs         map[string]string      `protobuf:"bytes,6,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels            map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BuildImageRequest) Reset() {
	*x = BuildImageRequest{}
	mi := &file_proto_image_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildImageRequest) ProtoMessage() {}

func (x *BuildImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildImageRequest.ProtoReflect.Descriptor instead.
func (*BuildImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{10}
}

func (x *BuildImageRequest) GetBuildContext() []byte {
	if x != nil {
		return x.BuildContext
	}
	return nil
}

func (x *BuildImageRequest) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

func (x *BuildImageRequest) GetDockerfileContent() string {
	if x != nil {
		return x.DockerfileContent
	}
	return ""
}

func (x *BuildImageRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BuildImageRequest) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

func (x *BuildImageRequest) GetBuildArgs() map[string]string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

func (x *BuildImageRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type BuildImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildImageResponse) Reset() {
	*x = BuildImageResponse{}
	mi := &file_proto_image_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildImageResponse) ProtoMessage() {}

func (x *BuildImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildImageResponse.ProtoReflect.Descriptor instead.
func (*BuildImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{11}
}

func (x *BuildImageResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PruneImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           string                 `protobuf:"bytes,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneImagesRequest) Reset() {
	*x = PruneImagesRequest{}
	mi := &file_proto_image_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneImagesRequest) ProtoMessage() {}

func (x *PruneImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneImagesRequest.ProtoReflect.Descriptor instead.
func (*PruneImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{12}
}

func (x *PruneImagesRequest) GetAll() string {
	if x != nil {
		return x.All
	}
	return ""
}

type PruneImagesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImagesDeleted  []*PruneImageResult    `protobuf:"bytes,1,rep,name=images_deleted,json=imagesDeleted,proto3" json:"images_deleted,omitempty"`
	SpaceReclaimed uint64                 `protobuf:"varint,2,opt,name=space_reclaimed,json=spaceReclaimed,proto3" json:"space_reclaimed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PruneImagesResponse) Reset() {
	*x = PruneImagesResponse{}
	mi := &file_proto_image_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneImagesResponse) ProtoMessage() {}

func (x *PruneImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneImagesResponse.ProtoReflect.Descriptor instead.
func (*PruneImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{13}
}

func (x *PruneImagesResponse) GetImagesDeleted() []*PruneImageResult {
	if x != nil {
		return x.ImagesDeleted
	}
	return nil
}

func (x *PruneImagesResponse) GetSpaceReclaimed() uint64 {
	if x != nil {
		return x.SpaceReclaimed
	}
	return 0
}

type PruneImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       string                 `protobuf:"bytes,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Untagged      string                 `protobuf:"bytes,2,opt,name=untagged,proto3" json:"untagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneImageResult) Reset() {
	*x = PruneImageResult{}
	mi := &file_proto_image_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneImageResult) ProtoMessage() {}

func (x *PruneImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneImageResult.ProtoReflect.Descriptor instead.
func (*PruneImageResult) Descriptor() ([]byte, []int) {
	return file_proto_image_proto_rawDescGZIP(), []int{14}
}

func (x *PruneImageResult) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

func (x *PruneImageResult) GetUntagged() string {
	if x != nil {
		return x.Untagged
	}
	return ""
}

var File_proto_image_proto protoreflect.FileDescriptor

const file_proto_image_proto_rawDesc = "" +
	"\n" +
	"\x11proto/image.proto\x12\bimage.v1\"$\n" +
	"\x10GetImagesRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"\x8d\x01\n" +
	"\x10GetImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1e\n" +
	"\n" +
	"containers\x18\x05 \x01(\x03R\n" +
	"containers\"G\n" +
	"\x11GetImagesResponse\x122\n" +
	"\x06images\x18\x01 \x03(\v2\x1a.image.v1.GetImageResponseR\x06images\"(\n" +
	"\x16GetImageDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc0\x01\n" +
	"\x17GetImageDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12\x18\n" +
	"\acreated\x18\x03 \x01(\tR\acreated\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\"a\n" +
	"\x12RemoveImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12%\n" +
	"\x0eprune_children\x18\x03 \x01(\bR\rpruneChildren\"L\n" +
	"\x13RemoveImageResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.image.v1.RemoveImageResultR\aresults\"I\n" +
	"\x11RemoveImageResult\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\tR\adeleted\x12\x1a\n" +
	"\buntagged\x18\x02 \x01(\tR\buntagged\"K\n" +
	"\x10PullImageRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12#\n" +
	"\rregistry_auth\x18\x02 \x01(\tR\fregistryAuth\")\n" +
	"\x11PullImageResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"\xbb\x03\n" +
	"\x11BuildImageRequest\x12#\n" +
	"\rbuild_context\x18\x01 \x01(\fR\fbuildContext\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tR\n" +
	"dockerfile\x12-\n" +
	"\x12dockerfile_content\x18\x03 \x01(\tR\x11dockerfileContent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x19\n" +
	"\bno_cache\x18\x05 \x01(\bR\anoCache\x12I\n" +
	"\n" +
	"build_args\x18\x06 \x03(\v2*.image.v1.BuildImageRequest.BuildArgsEntryR\tbuildArgs\x12?\n" +
	"\x06labels\x18\a \x03(\v2'.image.v1.BuildImageRequest.LabelsEntryR\x06labels\x1a<\n" +
	"\x0eBuildArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x12BuildImageResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"&\n" +
	"\x12PruneImagesRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\tR\x03all\"\x81\x01\n" +
	"\x13PruneImagesResponse\x12A\n" +
	"\x0eimages_deleted\x18\x01 \x03(\v2\x1a.image.v1.PruneImageResultR\rimagesDeleted\x12'\n" +
	"\x0fspace_reclaimed\x18\x02 \x01(\x04R\x0espaceReclaimed\"H\n" +
	"\x10PruneImageResult\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\tR\adeleted\x12\x1a\n" +
	"\buntagged\x18\x02 \x01(\tR\buntagged2\xd7\x03\n" +
	"\fImageService\x12D\n" +
	"\tGetImages\x12\x1a.image.v1.GetImagesRequest\x1a\x1b.image.v1.GetImagesResponse\x12V\n" +
	"\x0fGetImageDetails\x12 .image.v1.GetImageDetailsRequest\x1a!.image.v1.GetImageDetailsResponse\x12J\n" +
	"\vRemoveImage\x12\x1c.image.v1.RemoveImageRequest\x1a\x1d.image.v1.RemoveImageResponse\x12F\n" +
	"\tPullImage\x12\x1a.image.v1.PullImageRequest\x1a\x1b.image.v1.PullImageResponse0\x01\x12I\n" +
	"\n" +
	"BuildImage\x12\x1b.image.v1.BuildImageRequest\x1a\x1c.image.v1.BuildImageResponse0\x01\x12J\n" +
	"\vPruneImages\x12\x1c.image.v1.PruneImagesRequest\x1a\x1d.image.v1.PruneImagesResponseB\vZ\t./;protosb\x06proto3"

var (
	file_proto_image_proto_rawDescOnce sync.Once
	file_proto_image_proto_rawDescData []byte
)

func file_proto_image_proto_rawDescGZIP() []byte {
	file_proto_image_proto_rawDescOnce.Do(func() {
		file_proto_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_proto_rawDesc), len(file_proto_image_proto_rawDesc)))
	})
	return file_proto_image_proto_rawDescData
}

var file_proto_image_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_image_proto_goTypes = []any{
	(*GetImagesRequest)(nil),        // 0: image.v1.GetImagesRequest
	(*GetImageResponse)(nil),        // 1: image.v1.GetImageResponse
	(*GetImagesResponse)(nil),       // 2: image.v1.GetImagesResponse
	(*GetImageDetailsRequest)(nil),  // 3: image.v1.GetImageDetailsRequest
	(*GetImageDetailsResponse)(nil), // 4: image.v1.GetImageDetailsResponse
	(*RemoveImageRequest)(nil),      // 5: image.v1.RemoveImageRequest
	(*RemoveImageResponse)(nil),     // 6: image.v1.RemoveImageResponse
	(*RemoveImageResult)(nil),       // 7: image.v1.RemoveImageResult
	(*PullImageRequest)(nil),        // 8: image.v1.PullImageRequest
	(*PullImageResponse)(nil),       // 9: image.v1.PullImageResponse
	(*BuildImageRequest)(nil),       // 10: image.v1.BuildImageRequest
	(*BuildImageResponse)(nil),      // 11: image.v1.BuildImageResponse
	(*PruneImagesRequest)(nil),      // 12: image.v1.PruneImagesRequest
	(*PruneImagesResponse)(nil),     // 13: image.v1.PruneImagesResponse
	(*PruneImageResult)(nil),        // 14: image.v1.PruneImageResult
	nil,                             // 15: image.v1.BuildImageRequest.BuildArgsEntry
	nil,                             // 16: image.v1.BuildImageRequest.LabelsEntry
}
var file_proto_image_proto_depIdxs = []int32{
	1,  // 0: image.v1.GetImagesResponse.images:type_name -> image.v1.GetImageResponse
	7,  // 1: image.v1.RemoveImageResponse.results:type_name -> image.v1.RemoveImageResult
	15, // 2: image.v1.BuildImageRequest.build_args:type_name -> image.v1.BuildImageRequest.BuildArgsEntry
	16, // 3: image.v1.BuildImageRequest.labels:type_name -> image.v1.BuildImageRequest.LabelsEntry
	14, // 4: image.v1.PruneImagesResponse.images_deleted:type_name -> image.v1.PruneImageResult
	0,  // 5: image.v1.ImageService.GetImages:input_type -> image.v1.GetImagesRequest
	3,  // 6: image.v1.ImageService.GetImageDetails:input_type -> image.v1.GetImageDetailsRequest
	5,  // 7: image.v1.ImageService.RemoveImage:input_type -> image.v1.RemoveImageRequest
	8,  // 8: image.v1.ImageService.PullImage:input_type -> image.v1.PullImageRequest
	10, // 9: image.v1.ImageService.BuildImage:input_type -> image.v1.BuildImageRequest
	12, // 10: image.v1.ImageService.PruneImages:input_type -> image.v1.PruneImagesRequest
	2,  // 11: image.v1.ImageService.GetImages:output_type -> image.v1.GetImagesResponse
	4,  // 12: image.v1.ImageService.GetImageDetails:output_type -> image.v1.GetImageDetailsResponse
	6,  // 13: image.v1.ImageService.RemoveImage:output_type -> image.v1.RemoveImageResponse
	9,  // 14: image.v1.ImageService.PullImage:output_type -> image.v1.PullImageResponse
	11, // 15: image.v1.ImageService.BuildImage:output_type -> image.v1.BuildImageResponse
	13, // 16: image.v1.ImageService.PruneImages:output_type -> image.v1.PruneImagesResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_image_proto_init() }
func file_proto_image_proto_init() {
	if File_proto_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_proto_rawDesc), len(file_proto_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_proto_goTypes,
		DependencyIndexes: file_proto_image_proto_depIdxs,
		MessageInfos:      file_proto_image_proto_msgTypes,
	}.Build()
	File_proto_image_proto = out.File
	file_proto_image_proto_goTypes = nil
	file_proto_image_proto_depIdxs = nil
}
