// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/network.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworksRequest) Reset() {
	*x = GetNetworksRequest{}
	mi := &file_proto_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksRequest) ProtoMessage() {}

func (x *GetNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksRequest.ProtoReflect.Descriptor instead.
func (*GetNetworksRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{0}
}

type GetNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Created       string                 `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Driver        string                 `protobuf:"bytes,5,opt,name=driver,proto3" json:"driver,omitempty"`
	Internal      bool                   `protobuf:"varint,6,opt,name=internal,proto3" json:"internal,omitempty"`
	Attachable    bool                   `protobuf:"varint,7,opt,name=attachable,proto3" json:"attachable,omitempty"`
	Ingress       bool                   `protobuf:"varint,8,opt,name=ingress,proto3" json:"ingress,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkResponse) Reset() {
	*x = GetNetworkResponse{}
	mi := &file_proto_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkResponse) ProtoMessage() {}

func (x *GetNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{1}
}

func (x *GetNetworkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNetworkResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNetworkResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *GetNetworkResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetNetworkResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetNetworkResponse) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *GetNetworkResponse) GetAttachable() bool {
	if x != nil {
		return x.Attachable
	}
	return false
}

func (x *GetNetworkResponse) GetIngress() bool {
	if x != nil {
		return x.Ingress
	}
	return false
}

func (x *GetNetworkResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*GetNetworkResponse  `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworksResponse) Reset() {
	*x = GetNetworksResponse{}
	mi := &file_proto_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksResponse) ProtoMessage() {}

func (x *GetNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksResponse.ProtoReflect.Descriptor instead.
func (*GetNetworksResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{2}
}

func (x *GetNetworksResponse) GetNetworks() []*GetNetworkResponse {
	if x != nil {
		return x.Networks
	}
	return nil
}

type GetNetworkDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkDetailsRequest) Reset() {
	*x = GetNetworkDetailsRequest{}
	mi := &file_proto_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkDetailsRequest) ProtoMessage() {}

func (x *GetNetworkDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{3}
}

func (x *GetNetworkDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNetworkDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Created       string                 `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Driver        string                 `protobuf:"bytes,5,opt,name=driver,proto3" json:"driver,omitempty"`
	Internal      bool                   `protobuf:"varint,6,opt,name=internal,proto3" json:"internal,omitempty"`
	Attachable    bool                   `protobuf:"varint,7,opt,name=attachable,proto3" json:"attachable,omitempty"`
	Ingress       bool                   `protobuf:"varint,8,opt,name=ingress,proto3" json:"ingress,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkDetailsResponse) Reset() {
	*x = GetNetworkDetailsResponse{}
	mi := &file_proto_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkDetailsResponse) ProtoMessage() {}

func (x *GetNetworkDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{4}
}

func (x *GetNetworkDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNetworkDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNetworkDetailsResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *GetNetworkDetailsResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetNetworkDetailsResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetNetworkDetailsResponse) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *GetNetworkDetailsResponse) GetAttachable() bool {
	if x != nil {
		return x.Attachable
	}
	return false
}

func (x *GetNetworkDetailsResponse) GetIngress() bool {
	if x != nil {
		return x.Ingress
	}
	return false
}

func (x *GetNetworkDetailsResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Subnet        string                 `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Internal      bool                   `protobuf:"varint,5,opt,name=internal,proto3" json:"internal,omitempty"`
	Attachable    bool                   `protobuf:"varint,6,opt,name=attachable,proto3" json:"attachable,omitempty"`
	Ingress       bool                   `protobuf:"varint,7,opt,name=ingress,proto3" json:"ingress,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_proto_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNetworkRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CreateNetworkRequest) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *CreateNetworkRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *CreateNetworkRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *CreateNetworkRequest) GetAttachable() bool {
	if x != nil {
		return x.Attachable
	}
	return false
}

func (x *CreateNetworkRequest) GetIngress() bool {
	if x != nil {
		return x.Ingress
	}
	return false
}

func (x *CreateNetworkRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkResponse) Reset() {
	*x = CreateNetworkResponse{}
	mi := &file_proto_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkResponse) ProtoMessage() {}

func (x *CreateNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkResponse.ProtoReflect.Descriptor instead.
func (*CreateNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNetworkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConnectNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Settings      *EndpointSettings      `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectNetworkRequest) Reset() {
	*x = ConnectNetworkRequest{}
	mi := &file_proto_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectNetworkRequest) ProtoMessage() {}

func (x *ConnectNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectNetworkRequest.ProtoReflect.Descriptor instead.
func (*ConnectNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ConnectNetworkRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ConnectNetworkRequest) GetSettings() *EndpointSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type EndpointSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Aliases       []string               `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSettings) Reset() {
	*x = EndpointSettings{}
	mi := &file_proto_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSettings) ProtoMessage() {}

func (x *EndpointSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSettings.ProtoReflect.Descriptor instead.
func (*EndpointSettings) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{8}
}

func (x *EndpointSettings) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *EndpointSettings) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *EndpointSettings) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type ConnectNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectNetworkResponse) Reset() {
	*x = ConnectNetworkResponse{}
	mi := &file_proto_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectNetworkResponse) ProtoMessage() {}

func (x *ConnectNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectNetworkResponse.ProtoReflect.Descriptor instead.
func (*ConnectNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DisconnectNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectNetworkRequest) Reset() {
	*x = DisconnectNetworkRequest{}
	mi := &file_proto_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectNetworkRequest) ProtoMessage() {}

func (x *DisconnectNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectNetworkRequest.ProtoReflect.Descriptor instead.
func (*DisconnectNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{10}
}

func (x *DisconnectNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *DisconnectNetworkRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DisconnectNetworkRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DisconnectNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectNetworkResponse) Reset() {
	*x = DisconnectNetworkResponse{}
	mi := &file_proto_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectNetworkResponse) ProtoMessage() {}

func (x *DisconnectNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectNetworkResponse.ProtoReflect.Descriptor instead.
func (*DisconnectNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{11}
}

func (x *DisconnectNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PruneNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           string                 `protobuf:"bytes,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneNetworksRequest) Reset() {
	*x = PruneNetworksRequest{}
	mi := &file_proto_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneNetworksRequest) ProtoMessage() {}

func (x *PruneNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneNetworksRequest.ProtoReflect.Descriptor instead.
func (*PruneNetworksRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{12}
}

func (x *PruneNetworksRequest) GetAll() string {
	if x != nil {
		return x.All
	}
	return ""
}

type PruneNetworksResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NetworksDeleted []string               `protobuf:"bytes,1,rep,name=networks_deleted,json=networksDeleted,proto3" json:"networks_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PruneNetworksResponse) Reset() {
	*x = PruneNetworksResponse{}
	mi := &file_proto_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneNetworksResponse) ProtoMessage() {}

func (x *PruneNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneNetworksResponse.ProtoReflect.Descriptor instead.
func (*PruneNetworksResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{13}
}

func (x *PruneNetworksResponse) GetNetworksDeleted() []string {
	if x != nil {
		return x.NetworksDeleted
	}
	return nil
}

type RemoveNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkRequest) Reset() {
	*x = RemoveNetworkRequest{}
	mi := &file_proto_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkRequest) ProtoMessage() {}

func (x *RemoveNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkRequest.ProtoReflect.Descriptor instead.
func (*RemoveNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkResponse) Reset() {
	*x = RemoveNetworkResponse{}
	mi := &file_proto_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkResponse) ProtoMessage() {}

func (x *RemoveNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkResponse.ProtoReflect.Descriptor instead.
func (*RemoveNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_network_proto protoreflect.FileDescriptor

const file_proto_network_proto_rawDesc = "" +
	"\n" +
	"\x13proto/network.proto\x12\n" +
	"network.v1\"\x14\n" +
	"\x12GetNetworksRequest\"\xd5\x02\n" +
	"\x12GetNetworkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acreated\x18\x03 \x01(\tR\acreated\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x16\n" +
	"\x06driver\x18\x05 \x01(\tR\x06driver\x12\x1a\n" +
	"\binternal\x18\x06 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"attachable\x18\a \x01(\bR\n" +
	"attachable\x12\x18\n" +
	"\aingress\x18\b \x01(\bR\aingress\x12B\n" +
	"\x06labels\x18\t \x03(\v2*.network.v1.GetNetworkResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x13GetNetworksResponse\x12:\n" +
	"\bnetworks\x18\x01 \x03(\v2\x1e.network.v1.GetNetworkResponseR\bnetworks\"*\n" +
	"\x18GetNetworkDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe3\x02\n" +
	"\x19GetNetworkDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acreated\x18\x03 \x01(\tR\acreated\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x16\n" +
	"\x06driver\x18\x05 \x01(\tR\x06driver\x12\x1a\n" +
	"\binternal\x18\x06 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"attachable\x18\a \x01(\bR\n" +
	"attachable\x12\x18\n" +
	"\aingress\x18\b \x01(\bR\aingress\x12I\n" +
	"\x06labels\x18\t \x03(\v21.network.v1.GetNetworkDetailsResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x02\n" +
	"\x14CreateNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x16\n" +
	"\x06subnet\x18\x03 \x01(\tR\x06subnet\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\x12\x1a\n" +
	"\binternal\x18\x05 \x01(\bR\binternal\x12\x1e\n" +
	"\n" +
	"attachable\x18\x06 \x01(\bR\n" +
	"attachable\x12\x18\n" +
	"\aingress\x18\a \x01(\bR\aingress\x12D\n" +
	"\x06labels\x18\b \x03(\v2,.network.v1.CreateNetworkRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x15CreateNetworkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x93\x01\n" +
	"\x15ConnectNetworkRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x128\n" +
	"\bsettings\x18\x03 \x01(\v2\x1c.network.v1.EndpointSettingsR\bsettings\"l\n" +
	"\x10EndpointSettings\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\"2\n" +
	"\x16ConnectNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"r\n" +
	"\x18DisconnectNetworkRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"5\n" +
	"\x19DisconnectNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x14PruneNetworksRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\tR\x03all\"B\n" +
	"\x15PruneNetworksResponse\x12)\n" +
	"\x10networks_deleted\x18\x01 \x03(\tR\x0fnetworksDeleted\"&\n" +
	"\x14RemoveNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15RemoveNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xff\x04\n" +
	"\x0eNetworkService\x12N\n" +
	"\vGetNetworks\x12\x1e.network.v1.GetNetworksRequest\x1a\x1f.network.v1.GetNetworksResponse\x12`\n" +
	"\x11GetNetworkDetails\x12$.network.v1.GetNetworkDetailsRequest\x1a%.network.v1.GetNetworkDetailsResponse\x12T\n" +
	"\rCreateNetwork\x12 .network.v1.CreateNetworkRequest\x1a!.network.v1.CreateNetworkResponse\x12W\n" +
	"\x0eConnectNetwork\x12!.network.v1.ConnectNetworkRequest\x1a\".network.v1.ConnectNetworkResponse\x12`\n" +
	"\x11DisconnectNetwork\x12$.network.v1.DisconnectNetworkRequest\x1a%.network.v1.DisconnectNetworkResponse\x12T\n" +
	"\rPruneNetworks\x12 .network.v1.PruneNetworksRequest\x1a!.network.v1.PruneNetworksResponse\x12T\n" +
	"\rRemoveNetwork\x12 .network.v1.RemoveNetworkRequest\x1a!.network.v1.RemoveNetworkResponseB\vZ\t./;protosb\x06proto3"

var (
	file_proto_network_proto_rawDescOnce sync.Once
	file_proto_network_proto_rawDescData []byte
)

func file_proto_network_proto_rawDescGZIP() []byte {
	file_proto_network_proto_rawDescOnce.Do(func() {
		file_proto_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)))
	})
	return file_proto_network_proto_rawDescData
}

var file_proto_network_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_network_proto_goTypes = []any{
	(*GetNetworksRequest)(nil),        // 0: network.v1.GetNetworksRequest
	(*GetNetworkResponse)(nil),        // 1: network.v1.GetNetworkResponse
	(*GetNetworksResponse)(nil),       // 2: network.v1.GetNetworksResponse
	(*GetNetworkDetailsRequest)(nil),  // 3: network.v1.GetNetworkDetailsRequest
	(*GetNetworkDetailsResponse)(nil), // 4: network.v1.GetNetworkDetailsResponse
	(*CreateNetworkRequest)(nil),      // 5: network.v1.CreateNetworkRequest
	(*CreateNetworkResponse)(nil),     // 6: network.v1.CreateNetworkResponse
	(*ConnectNetworkRequest)(nil),     // 7: network.v1.ConnectNetworkRequest
	(*EndpointSettings)(nil),          // 8: network.v1.EndpointSettings
	(*ConnectNetworkResponse)(nil),    // 9: network.v1.ConnectNetworkResponse
	(*DisconnectNetworkRequest)(nil),  // 10: network.v1.DisconnectNetworkRequest
	(*DisconnectNetworkResponse)(nil), // 11: network.v1.DisconnectNetworkResponse
	(*PruneNetworksRequest)(nil),      // 12: network.v1.PruneNetworksRequest
	(*PruneNetworksResponse)(nil),     // 13: network.v1.PruneNetworksResponse
	(*RemoveNetworkRequest)(nil),      // 14: network.v1.RemoveNetworkRequest
	(*RemoveNetworkResponse)(nil),     // 15: network.v1.RemoveNetworkResponse
	nil,                               // 16: network.v1.GetNetworkResponse.LabelsEntry
	nil,                               // 17: network.v1.GetNetworkDetailsResponse.LabelsEntry
	nil,                               // 18: network.v1.CreateNetworkRequest.LabelsEntry
}
var file_proto_network_proto_depIdxs = []int32{
	16, // 0: network.v1.GetNetworkResponse.labels:type_name -> network.v1.GetNetworkResponse.LabelsEntry
	1,  // 1: network.v1.GetNetworksResponse.networks:type_name -> network.v1.GetNetworkResponse
	17, // 2: network.v1.GetNetworkDetailsResponse.labels:type_name -> network.v1.GetNetworkDetailsResponse.LabelsEntry
	18, // 3: network.v1.CreateNetworkRequest.labels:type_name -> network.v1.CreateNetworkRequest.LabelsEntry
	8,  // 4: network.v1.ConnectNetworkRequest.settings:type_name -> network.v1.EndpointSettings
	0,  // 5: network.v1.NetworkService.GetNetworks:input_type -> network.v1.GetNetworksRequest
	3,  // 6: network.v1.NetworkService.GetNetworkDetails:input_type -> network.v1.GetNetworkDetailsRequest
	5,  // 7: network.v1.NetworkService.CreateNetwork:input_type -> network.v1.CreateNetworkRequest
	7,  // 8: network.v1.NetworkService.ConnectNetwork:input_type -> network.v1.ConnectNetworkRequest
	10, // 9: network.v1.NetworkService.DisconnectNetwork:input_type -> network.v1.DisconnectNetworkRequest
	12, // 10: network.v1.NetworkService.PruneNetworks:input_type -> network.v1.PruneNetworksRequest
	14, // 11: network.v1.NetworkService.RemoveNetwork:input_type -> network.v1.RemoveNetworkRequest
	2,  // 12: network.v1.NetworkService.GetNetworks:output_type -> network.v1.GetNetworksResponse
	4,  // 13: network.v1.NetworkService.GetNetworkDetails:output_type -> network.v1.GetNetworkDetailsResponse
	6,  // 14: network.v1.NetworkService.CreateNetwork:output_type -> network.v1.CreateNetworkResponse
	9,  // 15: network.v1.NetworkService.ConnectNetwork:output_type -> network.v1.ConnectNetworkResponse
	11, // 16: network.v1.NetworkService.DisconnectNetwork:output_type -> network.v1.DisconnectNetworkResponse
	13, // 17: network.v1.NetworkService.PruneNetworks:output_type -> network.v1.PruneNetworksResponse
	15, // 18: network.v1.NetworkService.RemoveNetwork:output_type -> network.v1.RemoveNetworkResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_network_proto_init() }
func file_proto_network_proto_init() {
	if File_proto_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_network_proto_goTypes,
		DependencyIndexes: file_proto_network_proto_depIdxs,
		MessageInfos:      file_proto_network_proto_msgTypes,
	}.Build()
	File_proto_network_proto = out.File
	file_proto_network_proto_goTypes = nil
	file_proto_network_proto_depIdxs = nil
}
