// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/system.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{0}
}

type GetSystemInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServerVersion     string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	KernelVersion     string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	OperatingSystem   string                 `protobuf:"bytes,5,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Architecture      string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	NCpu              int32                  `protobuf:"varint,7,opt,name=n_cpu,json=nCpu,proto3" json:"n_cpu,omitempty"`
	MemTotal          int64                  `protobuf:"varint,8,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	Containers        int32                  `protobuf:"varint,9,opt,name=containers,proto3" json:"containers,omitempty"`
	ContainersRunning int32                  `protobuf:"varint,10,opt,name=containers_running,json=containersRunning,proto3" json:"containers_running,omitempty"`
	ContainersPaused  int32                  `protobuf:"varint,11,opt,name=containers_paused,json=containersPaused,proto3" json:"containers_paused,omitempty"`
	ContainersStopped int32                  `protobuf:"varint,12,opt,name=containers_stopped,json=containersStopped,proto3" json:"containers_stopped,omitempty"`
	Images            int32                  `protobuf:"varint,13,opt,name=images,proto3" json:"images,omitempty"`
	Driver            string                 `protobuf:"bytes,14,opt,name=driver,proto3" json:"driver,omitempty"`
	Labels            []string               `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSystemInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSystemInfoResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *GetSystemInfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *GetSystemInfoResponse) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *GetSystemInfoResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GetSystemInfoResponse) GetNCpu() int32 {
	if x != nil {
		return x.NCpu
	}
	return 0
}

func (x *GetSystemInfoResponse) GetMemTotal() int64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *GetSystemInfoResponse) GetContainers() int32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

func (x *GetSystemInfoResponse) GetContainersRunning() int32 {
	if x != nil {
		return x.ContainersRunning
	}
	return 0
}

func (x *GetSystemInfoResponse) GetContainersPaused() int32 {
	if x != nil {
		return x.ContainersPaused
	}
	return 0
}

func (x *GetSystemInfoResponse) GetContainersStopped() int32 {
	if x != nil {
		return x.ContainersStopped
	}
	return 0
}

func (x *GetSystemInfoResponse) GetImages() int32 {
	if x != nil {
		return x.Images
	}
	return 0
}

func (x *GetSystemInfoResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetSystemInfoResponse) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetDiskUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskUsageRequest) Reset() {
	*x = GetDiskUsageRequest{}
	mi := &file_proto_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskUsageRequest) ProtoMessage() {}

func (x *GetDiskUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskUsageRequest.ProtoReflect.Descriptor instead.
func (*GetDiskUsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{2}
}

type DiskUsageImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags      []string               `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Containers    int64                  `protobuf:"varint,4,opt,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsageImage) Reset() {
	*x = DiskUsageImage{}
	mi := &file_proto_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsageImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsageImage) ProtoMessage() {}

func (x *DiskUsageImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsageImage.ProtoReflect.Descriptor instead.
func (*DiskUsageImage) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{3}
}

func (x *DiskUsageImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiskUsageImage) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *DiskUsageImage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DiskUsageImage) GetContainers() int64 {
	if x != nil {
		return x.Containers
	}
	return 0
}

type DiskUsageContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	SizeRw        int64                  `protobuf:"varint,5,opt,name=size_rw,json=sizeRw,proto3" json:"size_rw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsageContainer) Reset() {
	*x = DiskUsageContainer{}
	mi := &file_proto_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsageContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsageContainer) ProtoMessage() {}

func (x *DiskUsageContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsageContainer.ProtoReflect.Descriptor instead.
func (*DiskUsageContainer) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{4}
}

func (x *DiskUsageContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiskUsageContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DiskUsageContainer) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DiskUsageContainer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiskUsageContainer) GetSizeRw() int64 {
	if x != nil {
		return x.SizeRw
	}
	return 0
}

type DiskUsageVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,2,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsageVolume) Reset() {
	*x = DiskUsageVolume{}
	mi := &file_proto_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsageVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsageVolume) ProtoMessage() {}

func (x *DiskUsageVolume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsageVolume.ProtoReflect.Descriptor instead.
func (*DiskUsageVolume) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{5}
}

func (x *DiskUsageVolume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskUsageVolume) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *DiskUsageVolume) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetDiskUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayersSize    int64                  `protobuf:"varint,1,opt,name=layers_size,json=layersSize,proto3" json:"layers_size,omitempty"`
	Images        []*DiskUsageImage      `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Containers    []*DiskUsageContainer  `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	Volumes       []*DiskUsageVolume     `protobuf:"bytes,4,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskUsageResponse) Reset() {
	*x = GetDiskUsageResponse{}
	mi := &file_proto_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskUsageResponse) ProtoMessage() {}

func (x *GetDiskUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskUsageResponse.ProtoReflect.Descriptor instead.
func (*GetDiskUsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{6}
}

func (x *GetDiskUsageResponse) GetLayersSize() int64 {
	if x != nil {
		return x.LayersSize
	}
	return 0
}

func (x *GetDiskUsageResponse) GetImages() []*DiskUsageImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GetDiskUsageResponse) GetContainers() []*DiskUsageContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *GetDiskUsageResponse) GetVolumes() []*DiskUsageVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

var File_proto_system_proto protoreflect.FileDescriptor

const file_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x12proto/system.proto\x12\tsystem.v1\"\x16\n" +
	"\x14GetSystemInfoRequest\"\xfd\x03\n" +
	"\x15GetSystemInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12)\n" +
	"\x10operating_system\x18\x05 \x01(\tR\x0foperatingSystem\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\x12\x13\n" +
	"\x05n_cpu\x18\a \x01(\x05R\x04nCpu\x12\x1b\n" +
	"\tmem_total\x18\b \x01(\x03R\bmemTotal\x12\x1e\n" +
	"\n" +
	"containers\x18\t \x01(\x05R\n" +
	"containers\x12-\n" +
	"\x12containers_running\x18\n" +
	" \x01(\x05R\x11containersRunning\x12+\n" +
	"\x11containers_paused\x18\v \x01(\x05R\x10containersPaused\x12-\n" +
	"\x12containers_stopped\x18\f \x01(\x05R\x11containersStopped\x12\x16\n" +
	"\x06images\x18\r \x01(\x05R\x06images\x12\x16\n" +
	"\x06driver\x18\x0e \x01(\tR\x06driver\x12\x16\n" +
	"\x06labels\x18\x0f \x03(\tR\x06labels\"\x15\n" +
	"\x13GetDiskUsageRequest\"q\n" +
	"\x0eDiskUsageImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1e\n" +
	"\n" +
	"containers\x18\x04 \x01(\x03R\n" +
	"containers\"\x81\x01\n" +
	"\x12DiskUsageContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\asize_rw\x18\x05 \x01(\x03R\x06sizeRw\"Y\n" +
	"\x0fDiskUsageVolume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x02 \x01(\tR\n" +
	"mountpoint\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xdf\x01\n" +
	"\x14GetDiskUsageResponse\x12\x1f\n" +
	"\vlayers_size\x18\x01 \x01(\x03R\n" +
	"layersSize\x121\n" +
	"\x06images\x18\x02 \x03(\v2\x19.system.v1.DiskUsageImageR\x06images\x12=\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\x1d.system.v1.DiskUsageContainerR\n" +
	"containers\x124\n" +
	"\avolumes\x18\x04 \x03(\v2\x1a.system.v1.DiskUsageVolumeR\avolumes2\xb4\x01\n" +
	"\rSystemService\x12R\n" +
	"\rGetSystemInfo\x12\x1f.system.v1.GetSystemInfoRequest\x1a .system.v1.GetSystemInfoResponse\x12O\n" +
	"\fGetDiskUsage\x12\x1e.system.v1.GetDiskUsageRequest\x1a\x1f.system.v1.GetDiskUsageResponseB\vZ\t./;protosb\x06proto3"

var (
	file_proto_system_proto_rawDescOnce sync.Once
	file_proto_system_proto_rawDescData []byte
)

func file_proto_system_proto_rawDescGZIP() []byte {
	file_proto_system_proto_rawDescOnce.Do(func() {
		file_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)))
	})
	return file_proto_system_proto_rawDescData
}

var file_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_system_proto_goTypes = []any{
	(*GetSystemInfoRequest)(nil),  // 0: system.v1.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil), // 1: system.v1.GetSystemInfoResponse
	(*GetDiskUsageRequest)(nil),   // 2: system.v1.GetDiskUsageRequest
	(*DiskUsageImage)(nil),        // 3: system.v1.DiskUsageImage
	(*DiskUsageContainer)(nil),    // 4: system.v1.DiskUsageContainer
	(*DiskUsageVolume)(nil),       // 5: system.v1.DiskUsageVolume
	(*GetDiskUsageResponse)(nil),  // 6: system.v1.GetDiskUsageResponse
}
var file_proto_system_proto_depIdxs = []int32{
	3, // 0: system.v1.GetDiskUsageResponse.images:type_name -> system.v1.DiskUsageImage
	4, // 1: system.v1.GetDiskUsageResponse.containers:type_name -> system.v1.DiskUsageContainer
	5, // 2: system.v1.GetDiskUsageResponse.volumes:type_name -> system.v1.DiskUsageVolume
	0, // 3: system.v1.SystemService.GetSystemInfo:input_type -> system.v1.GetSystemInfoRequest
	2, // 4: system.v1.SystemService.GetDiskUsage:input_type -> system.v1.GetDiskUsageRequest
	1, // 5: system.v1.SystemService.GetSystemInfo:output_type -> system.v1.GetSystemInfoResponse
	6, // 6: system.v1.SystemService.GetDiskUsage:output_type -> system.v1.GetDiskUsageResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_system_proto_init() }
func file_proto_system_proto_init() {
	if File_proto_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_proto_goTypes,
		DependencyIndexes: file_proto_system_proto_depIdxs,
		MessageInfos:      file_proto_system_proto_msgTypes,
	}.Build()
	File_proto_system_proto = out.File
	file_proto_system_proto_goTypes = nil
	file_proto_system_proto_depIdxs = nil
}
