// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/volume.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumesRequest) Reset() {
	*x = GetVolumesRequest{}
	mi := &file_proto_volume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumesRequest) ProtoMessage() {}

func (x *GetVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumesRequest.ProtoReflect.Descriptor instead.
func (*GetVolumesRequest) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{0}
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,3,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_proto_volume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{1}
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Volume) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *Volume) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumesResponse) Reset() {
	*x = GetVolumesResponse{}
	mi := &file_proto_volume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumesResponse) ProtoMessage() {}

func (x *GetVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumesResponse.ProtoReflect.Descriptor instead.
func (*GetVolumesResponse) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{2}
}

func (x *GetVolumesResponse) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *GetVolumesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type GetVolumeDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeDetailsRequest) Reset() {
	*x = GetVolumeDetailsRequest{}
	mi := &file_proto_volume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeDetailsRequest) ProtoMessage() {}

func (x *GetVolumeDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{3}
}

func (x *GetVolumeDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVolumeDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,3,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeDetailsResponse) Reset() {
	*x = GetVolumeDetailsResponse{}
	mi := &file_proto_volume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeDetailsResponse) ProtoMessage() {}

func (x *GetVolumeDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetVolumeDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{4}
}

func (x *GetVolumeDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVolumeDetailsResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetVolumeDetailsResponse) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *GetVolumeDetailsResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetVolumeDetailsResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetVolumeDetailsResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	DriverOpts    map[string]string      `protobuf:"bytes,3,rep,name=driver_opts,json=driverOpts,proto3" json:"driver_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_proto_volume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CreateVolumeRequest) GetDriverOpts() map[string]string {
	if x != nil {
		return x.DriverOpts
	}
	return nil
}

func (x *CreateVolumeRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,3,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_proto_volume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVolumeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CreateVolumeResponse) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *CreateVolumeResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateVolumeResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateVolumeResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RemoveVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVolumeRequest) Reset() {
	*x = RemoveVolumeRequest{}
	mi := &file_proto_volume_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVolumeRequest) ProtoMessage() {}

func (x *RemoveVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVolumeRequest.ProtoReflect.Descriptor instead.
func (*RemoveVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveVolumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveVolumeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RemoveVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVolumeResponse) Reset() {
	*x = RemoveVolumeResponse{}
	mi := &file_proto_volume_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVolumeResponse) ProtoMessage() {}

func (x *RemoveVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVolumeResponse.ProtoReflect.Descriptor instead.
func (*RemoveVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveVolumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PruneVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           string                 `protobuf:"bytes,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneVolumesRequest) Reset() {
	*x = PruneVolumesRequest{}
	mi := &file_proto_volume_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneVolumesRequest) ProtoMessage() {}

func (x *PruneVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneVolumesRequest.ProtoReflect.Descriptor instead.
func (*PruneVolumesRequest) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{9}
}

func (x *PruneVolumesRequest) GetAll() string {
	if x != nil {
		return x.All
	}
	return ""
}

type PruneVolumesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VolumesDeleted []string               `protobuf:"bytes,1,rep,name=volumes_deleted,json=volumesDeleted,proto3" json:"volumes_deleted,omitempty"`
	SpaceReclaimed uint64                 `protobuf:"varint,2,opt,name=space_reclaimed,json=spaceReclaimed,proto3" json:"space_reclaimed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PruneVolumesResponse) Reset() {
	*x = PruneVolumesResponse{}
	mi := &file_proto_volume_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneVolumesResponse) ProtoMessage() {}

func (x *PruneVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_volume_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneVolumesResponse.ProtoReflect.Descriptor instead.
func (*PruneVolumesResponse) Descriptor() ([]byte, []int) {
	return file_proto_volume_proto_rawDescGZIP(), []int{10}
}

func (x *PruneVolumesResponse) GetVolumesDeleted() []string {
	if x != nil {
		return x.VolumesDeleted
	}
	return nil
}

func (x *PruneVolumesResponse) GetSpaceReclaimed() uint64 {
	if x != nil {
		return x.SpaceReclaimed
	}
	return 0
}

var File_proto_volume_proto protoreflect.FileDescriptor

const file_proto_volume_proto_rawDesc = "" +
	"\n" +
	"\x12proto/volume.proto\x12\tvolume.v1\"\x13\n" +
	"\x11GetVolumesRequest\"\xc6\x01\n" +
	"\x06Volume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x03 \x01(\tR\n" +
	"mountpoint\x125\n" +
	"\x06labels\x18\x04 \x03(\v2\x1d.volume.v1.Volume.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x12GetVolumesResponse\x12+\n" +
	"\avolumes\x18\x01 \x03(\v2\x11.volume.v1.VolumeR\avolumes\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\")\n" +
	"\x17GetVolumeDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9f\x02\n" +
	"\x18GetVolumeDetailsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x03 \x01(\tR\n" +
	"mountpoint\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12G\n" +
	"\x06labels\x18\x06 \x03(\v2/.volume.v1.GetVolumeDetailsResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x02\n" +
	"\x13CreateVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12O\n" +
	"\vdriver_opts\x18\x03 \x03(\v2..volume.v1.CreateVolumeRequest.DriverOptsEntryR\n" +
	"driverOpts\x12B\n" +
	"\x06labels\x18\x04 \x03(\v2*.volume.v1.CreateVolumeRequest.LabelsEntryR\x06labels\x1a=\n" +
	"\x0fDriverOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\x14CreateVolumeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x03 \x01(\tR\n" +
	"mountpoint\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12C\n" +
	"\x06labels\x18\x06 \x03(\v2+.volume.v1.CreateVolumeResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x13RemoveVolumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"0\n" +
	"\x14RemoveVolumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x13PruneVolumesRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\tR\x03all\"h\n" +
	"\x14PruneVolumesResponse\x12'\n" +
	"\x0fvolumes_deleted\x18\x01 \x03(\tR\x0evolumesDeleted\x12'\n" +
	"\x0fspace_reclaimed\x18\x02 \x01(\x04R\x0espaceReclaimed2\xaa\x03\n" +
	"\rVolumeService\x12I\n" +
	"\n" +
	"GetVolumes\x12\x1c.volume.v1.GetVolumesRequest\x1a\x1d.volume.v1.GetVolumesResponse\x12[\n" +
	"\x10GetVolumeDetails\x12\".volume.v1.GetVolumeDetailsRequest\x1a#.volume.v1.GetVolumeDetailsResponse\x12O\n" +
	"\fCreateVolume\x12\x1e.volume.v1.CreateVolumeRequest\x1a\x1f.volume.v1.CreateVolumeResponse\x12O\n" +
	"\fRemoveVolume\x12\x1e.volume.v1.RemoveVolumeRequest\x1a\x1f.volume.v1.RemoveVolumeResponse\x12O\n" +
	"\fPruneVolumes\x12\x1e.volume.v1.PruneVolumesRequest\x1a\x1f.volume.v1.PruneVolumesResponseB\vZ\t./;protosb\x06proto3"

var (
	file_proto_volume_proto_rawDescOnce sync.Once
	file_proto_volume_proto_rawDescData []byte
)

func file_proto_volume_proto_rawDescGZIP() []byte {
	file_proto_volume_proto_rawDescOnce.Do(func() {
		file_proto_volume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_volume_proto_rawDesc), len(file_proto_volume_proto_rawDesc)))
	})
	return file_proto_volume_proto_rawDescData
}

var file_proto_volume_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_volume_proto_goTypes = []any{
	(*GetVolumesRequest)(nil),        // 0: volume.v1.GetVolumesRequest
	(*Volume)(nil),                   // 1: volume.v1.Volume
	(*GetVolumesResponse)(nil),       // 2: volume.v1.GetVolumesResponse
	(*GetVolumeDetailsRequest)(nil),  // 3: volume.v1.GetVolumeDetailsRequest
	(*GetVolumeDetailsResponse)(nil), // 4: volume.v1.GetVolumeDetailsResponse
	(*CreateVolumeRequest)(nil),      // 5: volume.v1.CreateVolumeRequest
	(*CreateVolumeResponse)(nil),     // 6: volume.v1.CreateVolumeResponse
	(*RemoveVolumeRequest)(nil),      // 7: volume.v1.RemoveVolumeRequest
	(*RemoveVolumeResponse)(nil),     // 8: volume.v1.RemoveVolumeResponse
	(*PruneVolumesRequest)(nil),      // 9: volume.v1.PruneVolumesRequest
	(*PruneVolumesResponse)(nil),     // 10: volume.v1.PruneVolumesResponse
	nil,                              // 11: volume.v1.Volume.LabelsEntry
	nil,                              // 12: volume.v1.GetVolumeDetailsResponse.LabelsEntry
	nil,                              // 13: volume.v1.CreateVolumeRequest.DriverOptsEntry
	nil,                              // 14: volume.v1.CreateVolumeRequest.LabelsEntry
	nil,                              // 15: volume.v1.CreateVolumeResponse.LabelsEntry
}
var file_proto_volume_proto_depIdxs = []int32{
	11, // 0: volume.v1.Volume.labels:type_name -> volume.v1.Volume.LabelsEntry
	1,  // 1: volume.v1.GetVolumesResponse.volumes:type_name -> volume.v1.Volume
	12, // 2: volume.v1.GetVolumeDetailsResponse.labels:type_name -> volume.v1.GetVolumeDetailsResponse.LabelsEntry
	13, // 3: volume.v1.CreateVolumeRequest.driver_opts:type_name -> volume.v1.CreateVolumeRequest.DriverOptsEntry
	14, // 4: volume.v1.CreateVolumeRequest.labels:type_name -> volume.v1.CreateVolumeRequest.LabelsEntry
	15, // 5: volume.v1.CreateVolumeResponse.labels:type_name -> volume.v1.CreateVolumeResponse.LabelsEntry
	0,  // 6: volume.v1.VolumeService.GetVolumes:input_type -> volume.v1.GetVolumesRequest
	3,  // 7: volume.v1.VolumeService.GetVolumeDetails:input_type -> volume.v1.GetVolumeDetailsRequest
	5,  // 8: volume.v1.VolumeService.CreateVolume:input_type -> volume.v1.CreateVolumeRequest
	7,  // 9: volume.v1.VolumeService.RemoveVolume:input_type -> volume.v1.RemoveVolumeRequest
	9,  // 10: volume.v1.VolumeService.PruneVolumes:input_type -> volume.v1.PruneVolumesRequest
	2,  // 11: volume.v1.VolumeService.GetVolumes:output_type -> volume.v1.GetVolumesResponse
	4,  // 12: volume.v1.VolumeService.GetVolumeDetails:output_type -> volume.v1.GetVolumeDetailsResponse
	6,  // 13: volume.v1.VolumeService.CreateVolume:output_type -> volume.v1.CreateVolumeResponse
	8,  // 14: volume.v1.VolumeService.RemoveVolume:output_type -> volume.v1.RemoveVolumeResponse
	10, // 15: volume.v1.VolumeService.PruneVolumes:output_type -> volume.v1.PruneVolumesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_volume_proto_init() }
func file_proto_volume_proto_init() {
	if File_proto_volume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_volume_proto_rawDesc), len(file_proto_volume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_volume_proto_goTypes,
		DependencyIndexes: file_proto_volume_proto_depIdxs,
		MessageInfos:      file_proto_volume_proto_msgTypes,
	}.Build()
	File_proto_volume_proto = out.File
	file_proto_volume_proto_goTypes = nil
	file_proto_volume_proto_depIdxs = nil
}
