spring:
  application:
    name: yadoma
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb+srv://doctrinefour_db_user:EGlZEIIG1SgXL22z@cluster0.2blb24a.mongodb.net/yadoma?retryWrites=true&w=majority
server:
  port: 8080
  servlet:
    context-path: /yadoma
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /
logging:
  level:
    dev:
      whiteo:
        yadoma: DEBUG
jwt:
  expiration:
    time: 720000
  secret:
    key: 1234567890ASDFGHJKLZXCVBNMASD123qwe1!!!!!!
app:
  version: "@project.version@"
grpc:
  host: ${GRPC_HOST}