spring:
  application:
    name: yadoma
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb+srv://localhost
server:
  port: 8080
  servlet:
    context-path: /yadoma
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /
logging:
  level:
    dev:
      whiteo:
        yadoma: DEBUG
jwt:
  expiration:
    time: EXPERIRE_TIME
  secret:
    key: SECRET_KEY
app:
  version: "@project.version@"
grpc:
  host: localhost