spring:
  application:
    name: yadoma
  main:
    banner-mode: off
  data:
    mongodb:
      uri: ${MONGO_URI}
server:
  port: ${PORT}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
logging:
  level:
    dev:
      whiteo:
        yadoma: ${APP_LOG_LEVEL}
jwt:
  expiration:
    time: ${TOKEN_EXPIRATION_TIME}
  secret:
    key: ${TOKEN_SECRET_KEY}
app:
  version: "@project.version@"
grpc:
  host: ${GRPC_HOST}