name: Build & Release

on:
  workflow_run:
    workflows: [ "Test" ]
    types: [ "completed" ]

concurrency:
  group: release-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/v')

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: whiteo/yadoma

    steps:
      - name: Download source of tested commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'
          check-latest: true

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Go
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        run: make install-deps

      - name: Generate protobuf files
        run: make generate

      - name: Build binary
        run: make build

      - name: Prepare release artifacts
        run: |
          git archive --format=zip --output build/yadoma-${GITHUB_REF_NAME}-src.zip HEAD
          mv build/yadoma-agent build/yadoma-agent-${GITHUB_REF_NAME}-linux-amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: make docker-push-agent
